messages:
  no-player: "&c{player} is not online"
  open-ender: "&dopen enderchest {player}"
  no-console: "&cOnly Player execute command"
  usage-openinv: "&cUsage : /openinv <jugador>"
  open-inv: "&dopen inventory {player}"
  no-item-hand: "&dNo item in hand"
  item-repair: "&dYou item repair"
  item-no-repair: "&dThis item no repair"
  mode-game-invalid: "&cUsage: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR"
  usage-gamemode: "&cUsage: /gamemode <modo> [jugador]"
  gamemode-change: "&cYour game mode has been changed to {gamemode}"
  gamemode-change-target: "&cYou have changed the game mode of {player} to {gamemode}"
  usage-tpa: "&cUso: /tpa <jugador>"
  tpa-yourself: "&cNo tpa yourself"
  tpa-sent: "&cYou have sent a teleport request to {target}"
  tpa-received: "&d{player} want to teleport to you. Use /tpaccept to accept or /tpdeny to reject"
  tpa-expired: "&dYour request for teleportation to {target} expired"
  tpa-expired-target: "&dThe teleportation request of {target} expired"