name: SimpleCommands
version: '${project.version}'
main: com.chillguy.simplecommands.Main
api-version: '1.20'
commands:
  trash:
    description: Trash Command
  tpa:
    description: Tpa command
  openinv:
    description: Open inv
  god:
    description: God mode
  gamemode:
    description: Game mode
  fix:
    description: Fix item
  enderchest:
    description: Ender chest